### ISSUE TITLE
How can I resume training from a checkpoint?

### ISSUE THREAD

**Issue by MusfiqDehan** [neulab/awesome#42]
Hi,
First of all thanks for these amazing tools and amazing documentation. I am training `awesome_align` using a parallel corpus. My dataset is quite large. Is there any way to resume training from `checkpoint`? During training, many checkpoints are being created in the `Output ` directory (`checkpoint-4000`, `checkpoint-8000` etc). How can I use those checkpoints?

Thanks in advance.

**Comment by zdou0830** [comment]
Hi, this issue https://github.com/neulab/awesome-align/issues/39 may be helpful.
