### ISSUE TITLE
Abort experiment in Table 8

### ISSUE THREAD

**Issue by sdongchuanqi** [neulab/awesome#45]
Hellow ,I noticed that you compaired your result with  GIZA++/fast_align in the expirment **AnnotationProjection** . So how do you get the paralled sentences of english-spanish to train this models? Using GoogleTranslate to translate English train dataset to Spanish train dataset?

**Comment by zdou0830** [comment]
Hi, I directly finetuned it on the NER English-Spanish test parallel data.

**Comment by sdongchuanqi** [comment]
even in giza++ and fastalign? ok  thanks you

**Comment by zdou0830** [comment]
Yes.
