### ISSUE TITLE
Alignment prob matrix visualization tool?

### ISSUE THREAD

**Issue by kirklandWater1** [neulab/awesome#50]
Hi,

Thank you so much for the great alignment tool! I was wondering that would it be possible for you to share some tools/code that you use to produce the alignment prob matrix like the following picture?

<img width="375" alt="image" src="https://user-images.githubusercontent.com/97708066/190486883-599687ab-6c2e-4cbc-aae5-7d8363b3df1c.png">

Thanks!

**Comment by zdou0830** [comment]
Hi, I used [seaborn](https://seaborn.pydata.org/) to draw the figure. I used seaborn.heatmap to generate the heat maps and axvline/axhline to generate the red lines.

**Comment by kirklandWater1** [comment]
Thanks a lot!!
